name: Testing Workflow

on:
  push:
    branches:
      - main

jobs:
  matrix:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.9
          uses: actions/setup-python@v5
          with:
            python-version: 3.9
        - run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run tests
          run: python main.py
